spring.application.name=backend

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8080

inventory.low-stock-threshold=5

supplier.base-url=https://legacysupply.onrender.com/api/v1
supplier.client-id=${LS_CLIENT_ID}
supplier.api-key=${LS_API_KEY}

supplier.retry-delay-ms=60000
supplier.tracking-delay-ms=60000

# ==================================================
# TIANGGE / LAB 4
# ==================================================

channel.tiangge.base-url=https://legacysupply.onrender.com/tiangge/v1

channel.tiangge.client-id=${LS_CLIENT_ID}
channel.tiangge.api-key=${LS_API_KEY}

channel.tiangge.app-name=garciano-shop

channel.tiangge.heartbeat-ms=30000

channel.tiangge.feed-poll-ms=3000
channel.tiangge.feed-initial-delay-ms=5000
channel.tiangge.stock-retry-ms=5000
channel.tiangge.backorder-retry-ms=5000